In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("diabetes.csv")#to load data set

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.isnull().sum()#to check null values

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.dtypes #to check 

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [6]:
df.duplicated().sum()

0

In [7]:
df.describe()#we get a better understanding of the dataset

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
df['Outcome'].value_counts()#To check how many people have diabetes and how many donot

Outcome
0    500
1    268
Name: count, dtype: int64

In [9]:
#select the input and output from the dataset
X=df.drop("Outcome",axis=1)#input
Y=df["Outcome"]#output

In [10]:
#Train and test the model with 70% and 30%
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.7,random_state=1)

In [11]:
X_train.shape

(230, 8)

In [12]:
Y_train.shape

(230,)

In [13]:
#create object of StandardScaler
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit_transform(X_train)
ss.transform(X_test)

array([[ 0.91971608,  0.44644081,  0.28333417, ..., -0.81204064,
         0.75226945,  1.6530127 ],
       [-0.85292106,  0.93200853, -0.4147041 , ..., -0.79875879,
        -0.90205633, -0.9609263 ],
       [ 0.62427656, -0.42758108, -0.4147041 , ..., -0.94485912,
        -0.80661445, -0.51024716],
       ...,
       [ 1.2151556 ,  0.05798664,  0.38305392, ..., -0.45343074,
         0.89366482,  1.74314853],
       [-0.85292106, -1.01026234, -0.2152646 , ..., -0.3870215 ,
        -0.85610283, -1.05106213],
       [ 0.03339751,  0.6406679 ,  0.88165268, ...,  1.578692  ,
         0.74519969, -0.9609263 ]])

In [14]:
#Use logistic regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(X_train,Y_train)

LogisticRegression()

In [15]:
#Test the model with 30% data
Y_pred=lr.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,

In [16]:
dict={'Actual output':Y_test,'Predicted output':Y_pred}
df1=pd.DataFrame(dict)
df1

Actual output  Predicted output
285              0                 0
101              0                 0
581              0                 0
352              0                 0
726              0                 0
..             ...               ...
182              0                 0
300              1                 1
584              1                 1
240              0                 0
230              1                 1

[538 rows x 2 columns]

In [17]:
#confusion_matrix inbuilt class   : create report of classification
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y_test,Y_pred))

[[305  49]
 [ 72 112]]


In [18]:
#check all score (Recall ,precision,accuracy anf F1-score)
#inbuilt class classification_report
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.81      0.86      0.83       354
           1       0.70      0.61      0.65       184

    accuracy                           0.78       538
   macro avg       0.75      0.74      0.74       538
weighted avg       0.77      0.78      0.77       538



In [19]:
#Call DecisionTreeClassifier class  : inbuilt class
#model train with the help of DecisionTreeClassifier class

from sklearn.tree import DecisionTreeClassifier

In [20]:
#create the object of DecisionTreeClassifier class
dt=DecisionTreeClassifier(random_state=1) #use method gini index
#train the model from DecisionTreeClassifier class with 70% training input and training output
dt.fit(X_train,Y_train)

DecisionTreeClassifier(random_state=1)

In [21]:
#to check information gain from each input to find the output variable
dt.feature_importances_

array([0.05761024, 0.25562042, 0.09503288, 0.06708918, 0.02500544,
       0.16067113, 0.13624346, 0.20272726])

In [22]:
dict={'Input Columns':X.columns,'IG':dt.feature_importances_ }
#IG means information Gain
#convert dictionary into DataFrame
df1=pd.DataFrame(dict)
df1

Input Columns        IG
0               Pregnancies  0.057610
1                   Glucose  0.255620
2             BloodPressure  0.095033
3             SkinThickness  0.067089
4                   Insulin  0.025005
5                       BMI  0.160671
6  DiabetesPedigreeFunction  0.136243
7                       Age  0.202727

In [23]:
#Test the model with 30% data,
Y_pred=dt.predict(X_test)
Y_pred


array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,

In [24]:
#Report Generate
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[260  94]
 [ 90  94]]
              precision    recall  f1-score   support

           0       0.74      0.73      0.74       354
           1       0.50      0.51      0.51       184

    accuracy                           0.66       538
   macro avg       0.62      0.62      0.62       538
weighted avg       0.66      0.66      0.66       538



In [25]:
#create object of decisiontreeclassifier class and passing the parameter for
dt1=DecisionTreeClassifier(random_state=1,criterion='entropy')
#by default criteron parameter='gini'

In [26]:
#train the model with 70% training data
dt1.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', random_state=1)

In [27]:
dict={'Input Columns':X.columns,'IG':dt1.feature_importances_ }
#IG means information Gain
#convert dictionary into DataFrame
df1=pd.DataFrame(dict)
#sorting dataframe df1 according to IG column in descending order
#use inbuilt method sort_values() of pandas library
df1.sort_values('IG',ascending=False) #by default ascending=True means ascending order

Input Columns        IG
7                       Age  0.294881
5                       BMI  0.257628
1                   Glucose  0.214973
6  DiabetesPedigreeFunction  0.090737
4                   Insulin  0.050875
2             BloodPressure  0.037954
0               Pregnancies  0.030522
3             SkinThickness  0.022428

In [28]:
#test the model with 30% data, use inbuilt method predict() of decisionTee
Y_pred=dt1.predict(X_test)

In [29]:
#generate report
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[273  81]
 [ 97  87]]
              precision    recall  f1-score   support

           0       0.74      0.77      0.75       354
           1       0.52      0.47      0.49       184

    accuracy                           0.67       538
   macro avg       0.63      0.62      0.62       538
weighted avg       0.66      0.67      0.67       538

